port: "6789"

otel:
  grpc_address: "127.0.0.1:4317"

log:
  dir: "logs"
  name: "bluebird.log"
  level: "debug"
  max_size: 20      #一个文件最大可达 20M
  max_backups: 5   # 最多同时保存 5 个文件
  max_age: 10     # 一个文件最多可以保存 10 天
  compress: true  # 用 gzip 压缩