basePath: /
host: localhost:8888
info:
  contact:
    name: bluebird
    url: https://github.com/stonebridjx/bluebird
  description: Blue is a gentle, comforting color, and the blue bird symbolizes happiness
    and freedom.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: stonebridjx/bluebird
  version: 1.0.0
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试Description
      produces:
      - application/json
      responses: {}
      summary: 测试Summary
schemes:
- http
swagger: "2.0"
